### ISSUE TITLE
IRremote conflict

### ISSUE THREAD

**Issue by f15h35** [PowerBroker2/DFPlayerMini_Fast#41] opened 2021-05-04 15:19 UTC
I am having trouble compiling a sketch. Maybe a conflict with the IRremote library? My sketch was previously working with the DFRobotDFPlayerMini library. I am getting the following error:

Arduino: 1.8.12 (Linux), Board: "Arduino Pro or Pro Mini, ATmega328P (5V, 16 MHz)"

In file included from /home/Arduino/remote_codes/remote_codes.ino:1:0:
/home/Arduino/libraries/IRremote/src/IRremote.h:188:16: error: expected unqualified-id before numeric constant
 #define REPEAT 0xFFFFFFFF

/home/Arduino/libraries/DFPlayerMini_Fast/src/DFPlayerMini_Fast.h:99:16: note: in expansion of macro 'REPEAT'
  const uint8_t REPEAT          = 0;

exit status 1
Error compiling for board Arduino Pro or Pro Mini.

**Comment by PowerBroker2** [comment] 2021-05-04 22:10
The problem is the person who wrote IRremote.h is using #defines instead of const declarations, which is a terrible coding practice. IMO, that library is the one that should be fixed, but thank you for bringing this to my attention. Submit an issue to that library and have them fix their sub-par code.

If you want a workaround, replace one of the names in one of the libraries to something like `_REPEAT_`. Make sure every instance is replaced.

**Closed by PowerBroker2** 2021-05-04 22:10 UTC
